server:
  port: 9002

spring:
  security:
    oauth2:
      client:
        registration:
          boxcom:
            provider:                     "boxcom"
            client-name:                  "Box.com"
            client-id:                    "input here"
            client-secret:                "input here"
            authorization-grant-type:     "authorization_code"
            client-authentication-method: "POST"
            redirect-uri:                 "{baseUrl}/login/oauth2/code/{registrationId}"

        provider: 
          boxcom:
            authorization-uri:   "https://account.box.com/api/oauth2/authorize/"
            token-uri:           "https://api.box.com/oauth2/token/"
            user-info-uri:       "https://api.box.com/2.0/users/me/"
            user-name-attribute: "id"

  thymeleaf:
    cache: false

logging:
  level:
    root: info
    org.springframework.http.codec.json: info
   
